name: Terraform Variables CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  tf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.0"

      - name: Validar formato
        run: terraform fmt -check

      - name: Validar configuración
        run: terraform validate

      - name: Generar plan
        run: terraform plan -var-file="terraform.tfvars"
